package git_hub_sumair_app1.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import git_hub_sumair_app1.controller.dto.User;
import git_hub_sumair_app1.database.repository.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class DbController {

	
		@Autowired // This means to get the bean called userRepository
		           // Which is auto-generated by Spring, we will use it to handle the data
		private UserRepository userRepository;

		@GetMapping(path="/add") // Map ONLY GET Requests
		public @ResponseBody String addNewUser (@RequestParam String name,@RequestParam int id
				, @RequestParam String email, @RequestParam String cc, @RequestParam String pn) {
			// @ResponseBody means the returned Strisng is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request

			User user = new User();
			user.setId(id);
			user.setName(name);
			user.setEmail(email);
			user.setCountryCode(cc);
			user.setPhoneNumber(pn);
			userRepository.save(user);
			return "Saved";
		}

		@GetMapping(path="/all")
		public @ResponseBody Iterable<User> getAllUsers() {
			// This returns a JSON or XML with the users
			return userRepository.findAll();
		}	
}
